import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/trip_plan_model.dart';

class PdfService {
  static Future<void> generateAndShareTripPdf(TripPlan plan) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text("TripMe.ai - Your Oracle Guided Journey", 
              style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
          ),
          pw.SizedBox(height: 20),
          pw.Text("Destination: ${plan.tripSummary.destinationCity}",
            style: pw.TextStyle(fontSize: 18)),
          pw.Text("Duration: ${plan.itinerary.length} Days", 
            style: pw.TextStyle(fontSize: 14)),
          pw.SizedBox(height: 30),
          
          pw.Text("THE ORACLE'S VISION", style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.Divider(),
          pw.Text(plan.humanText, style: const pw.TextStyle(fontSize: 12, lineSpacing: 2)),
          pw.SizedBox(height: 30),

          pw.Text("ITINERARY", style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.Divider(),
          ...plan.itinerary.map((day) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.SizedBox(height: 15),
              pw.Text("Day ${day.day}: ${day.dayTheme}", style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 5),
              ...day.items.map((item) => pw.Bullet(
                text: "${item.time} - ${item.title}: ${item.notes}",
                style: const pw.TextStyle(fontSize: 10),
              )),
            ],
          )),
          
          pw.SizedBox(height: 40),
          pw.Footer(
            trailing: pw.Text("Generated by TripMe.ai", style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
          ),
        ],
      ),
    );

    await Printing.sharePdf(bytes: await pdf.save(), filename: 'tripme_itinerary.pdf');
  }
}
